name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: todo-app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Build Release APK (unsigned)
        run: ./gradlew assembleRelease
        continue-on-error: true

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: todo-app-release-unsigned
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 30
